[project]
name = "granite_geo_flood"
version = "1.0.0"
description = "Granite Flood Segmentation Model with S1 and S2 bands"
license = { text = "Apache License, Version 2.0" }
readme = "README.md"
requires-python = ">=3.10"

